name: build and test
on:
  push:
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version: 1.19
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
      - name: restore_cache
        uses: actions/cache@69d9d449aced6a2ede0bc19182fadc3a0a42d2b0 # v3.2.6
        with:
          key: go-mod-v1-{{ checksum "go.sum" }}
          restore-keys: go-mod-v1-{{ checksum "go.sum" }}
          path: "/go/pkg/mod"
      - run: go mod download
      - run: go mod tidy
      - name: Run go format
        run: |-
          files=$(go fmt ./...)
          if [ -n "$files" ]; then
            echo "The following file(s) do not conform to go fmt:"
            echo "$files"
            exit 1
          fi
      - name: Build
        run: go build -v ./...
      - name: Run unit tests
        run: |- 
          go test -v -race -coverprofile cover.out.tmp ./...
          grep -v "_mock.go" < cover.out.tmp > cover.out
          go tool cover -func=cover.out
permissions:
  contents: read
